name: Main Branch

on:
  push:
     branches: [ main ]

jobs:

 
  release-notes:
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Generate and email notes
          uses: patrixr/jira-release-notes@v1.0.1
          id: pdf_generator
          with:
            head: ${{github.event.push.head.sha}}
            base: ${{github.event.push.base.sha}}
            jira-code: 'JUDE'
            jira-host: judebantony.atlassian.net
            jira-username: 'judebantony'
            jira-password: ${{secrets.JIRA_GITHUB_ACTION_TOKEN}}
            app-name: 'My GitHub Action Service'
            unshallow: true
        - name: Process the pdf
          run: echo "The generated pdf was ${{ steps.pdf_generator.outputs.pdf }}"