name: Main Branch

on:
  push:
     branches: [ main ]

jobs:

 
 opa-test:
    name: IaC Scan Using OPA
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: OPA-Test manifests standards.
          uses: ameydev/ci-cd-standards-using-opa@master
          env:
            MANIFESTS_PATH_PATTERN: manifests/
            LIBRARY_PATH: opa-policies/ci-standards 
            DATA: data.kubernetes.admission.deny 
