name: Master Branch

on:
  push:
    branches:
      - 'main'

jobs:

  test:
    name: Build And UnitTest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify -DskipTests
      - name: Maven Test
        run: mvn -B test
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          author_name: judebantony
          author_email: judebantony@gmail.com
          committer_name: judebantony
          committer_email: judebantony@gmail.com
          default_author: judebantony@users.noreply.github.com
          message: 'commit badge'
          add: '*.svg'          
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/
      - name: Send report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Test Coverage of ${{github.repository}} repo
          to: judebantony@gmail.com
          from: judebantonyofficial@gmail.com
          body: Build job of ${{github.repository}} completed successfully!
          html_body: file://target/site/jacoco/index.html
          reply_to: judebantonyofficial@gmail.com
          in_reply_to: judebantonyofficial@gmail.com
          ignore_cert: true
          convert_markdown: true
          priority: low